services:
  backend:
    build: .
    container_name: backend-nompi
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:1234@postgres:5432/nompi_db?schema=public"
    volumes: 
      - .:/backend-nompi
      - /backend-nompi/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-nompi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nompi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
